import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Content, Header, MainLayout } from "@layout";

const SpoqaThin = localFont({
  src: "./fonts/SpoqaHanSansNeo-Thin.woff2",
  variable: "--font-spoqa-thin",
  weight: "100",
});

// 기본
const SpoqaRegular = localFont({
  src: "./fonts/SpoqaHanSansNeo-Regular.woff2",
  variable: "--font-spoqa-regular",
  weight: "900",
});

// 두꺼운 폰트
const SpoqaBold = localFont({
  src: "./fonts/SpoqaHanSansNeo-Bold.woff2",
  variable: "--font-spoqa-bold",
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${SpoqaThin.variable} ${SpoqaRegular.variable} ${SpoqaBold.variable} antialiased`}
      >
        <MainLayout>
          <Header />
          <Content>{children}</Content>
        </MainLayout>
      </body>
    </html>
  );
}
