import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Container from "./Container/Container";
import Header from "./Header/Header";
import Inner from "./Inner/Inner";
import localFont from "next/font/local";

const SpoqaThin = localFont({
  src: "../fonts/SpoqaHanSansNeo-Thin.woff2",
  variable: "--font-spoqa-thin",
  weight: "100",
});

// 기본
const SpoqaRegular = localFont({
  src: "../fonts/SpoqaHanSansNeo-Regular.woff2",
  variable: "--font-spoqa-regular",
  weight: "900",
});

// 두꺼운 폰트
const SpoqaBold = localFont({
  src: "../fonts/SpoqaHanSansNeo-Bold.woff2",
  variable: "--font-spoqa-bold",
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={` ${SpoqaThin.variable} ${SpoqaRegular.variable} ${SpoqaBold.variable} antialiased`}>
        <Container>
          <Header />
          <Inner>{children}</Inner>
        </Container>
      </body>
    </html>
  );
}
